### ISSUE TITLE
goocanvas-2.0 should never be used

### ISSUE THREAD

**Issue by paulfertser** [osm2go/osm2go#11]
When compiling on a system with only goocanvas-2.0 is installed everything is getting built fine but then it fails runtime because goocanvas-2.0 depends on Gtk+-3.0 (see their commit d3d9b6038ef003883091d4a91cfa59c0e2639e3b) and osm2go uses Gtk+-2.0 and they can't be mixed in a single executable.

**Comment by DerDakon** [comment]
Fixed in 2f02f0093a0be774a3bdf03604207fdbe9e97086.
