### ISSUE TITLE
add installation instructions

### ISSUE THREAD

**Issue by mfrasca** [osm2go/osm2go#20]
hi here, so happy to see osm2go back on its feet.
I am not so sure how to install it successfully though.
I did the following:

* download the three `deb` files: 
  * `openssl_1.0.2o-1.maemo1.0osm2go0_armel.deb`
  * `libssl1.0.2_1.0.2o-1.maemo1.0osm2go0_armel.deb`
  * `osm2go_0.9.15-maemo1_armel.deb`
* copy them to my N900, in a fresh, empty directory
* log in as root
* `cd` to the new fresh directory
* `dpkg -i *.deb`
  this will report the missing package `libgoocanvas3`.
* `apt-get install libgoocanvas3`
  this will complain about unmet dependencies.
* `apt-get -f install`
  this completes the installation, and I can start osm2go.

but now I am stuck with issue #19.  and I do not so promptly recognize what I should do.

**Comment by DerDakon** [comment]
You should now use the 1.0.2u packages I released some minutes ago, as well as the extra-ca-certificates package at the same location. This should help.

**Comment by mfrasca** [comment]
would you process my instructions into the front page?  if necessary, update them?
I am reviewing them myself, but I am sure you can be more precise, and maybe can explain why each step is necessary, and which is the best repeatable sequence.

**Comment by DerDakon** [comment]
Yes, I will put them into the wiki.
