### ISSUE TITLE
Project selection needs filter field

### ISSUE THREAD

**Issue by DerDakon** [osm2go/osm2go#7]
When you have more than 10-15 projects it becomes clumsy to scroll up and down to find the right project. A filter field where one could enter a few chars to drastically reduce the number of currently shown projects would make things much easier.

**Comment by AMDmi3** [comment]
I think it would be also nice to implement project autoswitching based on GPS position.

**Comment by DerDakon** [comment]
Like in #3...

**Comment by DerDakon** [comment]
Since 305d2dd4b507a9668f7257cc8103b655b391f508 the project list is sorted alphabetically, which greatly reduces the pain.

**Comment by DerDakon** [comment]
Done in 2b6b88e79ef49352501ce4fcb09877583877625e.
